### ISSUE TITLE
Ain't working no more

### ISSUE THREAD

**Issue by Anothuoretta** [thedoomed/Cheat-Engine#10]
What happened? 

![image](https://user-images.githubusercontent.com/89801108/161372076-dcb60aaa-c48e-4371-b30b-6d8a86f596d4.png)

**Comment by Anothuoretta** [comment]
This is still happening

**Comment by bloxain** [comment]
Use the Correct Roblox the open task manager find the "RobloxPlayerBeta.exe" using less ram then end it with task manager and boom now open the correct Roblox.

https://www.youtube.com/watch?v=rNvr7-kufag for help
