### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by Anothuoretta** [thedoomed/Cheat-Engine#6]
Its not working for me anymore? When I execute it doesnt even give me a console message. It says
 'Error:[string "util = {};..."]:114: attempt to index a nil value (local 'results')
Script Error
'

**Comment by Mark-Benson** [comment]
how do you fix it?

**Comment by jLn0n** [comment]
maybe update the addys and idk

**Comment by thedoomed** [comment]
I will be updating this shortly. I did some major rewriting to it so it's no longer an LBI -- it will use cheat engine's own Lua Engine to run scripts by transpiling the existing lua environment in cheat engine.
It will also support custom functions, making it the most complete executor for roblox on cheat engine today. 👍

**Comment by jLn0n** [comment]
pogggg
